import Head from 'next/head';

import Header from '../components/Header';
import {useCallback, useEffect, useState} from 'react';
import {useRouter} from 'next/router';
import axios from 'axios';

let NEXT_APP_DEV = true

function Home() {
  const router = useRouter()

   const [devicesList, setDeviceList] = useState([]);

   function goToPath(path) {
    console.log('path: ',path)
    router.push(`devices/${path}`)
    //if(NEXT_APP_DEV) router.push(`devices?deviceName=${path}`) 
   }

   const axiosLoadDeviceList = useCallback( async () => {
    axios.get('/api/devices?device=all').then((res) => {
       console.log(res.data)
      setDeviceList(res.data);
      return res.data;
    });
 })

 useEffect(() => {
  axiosLoadDeviceList((res)=>res);
  return
}, []);


  return (
    <>
     <Head>
         <title>Homatic ccu3 app</title>
         <meta name="description" content="Generated by create next app" />
         <link rel="icon" href="/favicon.ico" />
       </Head>

      {/* <Header></Header> */}
       <div>
        <select
          onChange={(e) =>{
            console.log('onclick select: ',e)
            goToPath(e.target.value)}}
        >
          <option value={'/'}>please chooice</option>
          {
            devicesList.map((device)=>{
              return <option key={device} value={`${device}`}>{device}</option>
            })
          }
        </select>

        <h1>das ist meine ccu xml-api app</h1>
        <p></p>
        
       </div>
    </>
  );
}

export default Home;



/* geht nur mit fixen URLs*/
// export async function getStaticProps(){
//   const DevicesOptionList = await fetch('/api/devices')
//   return{
//     props:{
//       DevicesOptionList
//     }
//   }
// }
