import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Header from '../components/Header';
import {useCallback, useEffect, useState} from 'react';
import {useRouter} from 'next/router';
import axios from 'axios';
import Option from '../components/Option';

import Link from 'next/link';
import ROUTES from '../config/ROUTES';

function Home() {
  // const router = useRouter()

  // const [devicesList, setDeviceList] = useState("default");
  // function goToPath(path) {
  //   router.push('/'+path)
  //   console.log('path',path);
  // }

  // const axiosLoadDeviceList = async () => {
  //   axios.get('/api/devices?device=all').then((res) => {

  //     console.log('res.data: ',res.data)
  //     setDeviceList(JSON.stringify(res.data ));
  //     return res.data;
  //   });
  // };

  // useEffect(() => {
  //   axiosLoadDeviceList();
  // }, []);

  // /*
  // onLoad funktioniert nicht warum auch immer
  // */
  // return (
  //   <>
  //     <Head>
  //       <title>Homatic ccu3 app</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>
  //     <div>
  //       <select
  //         onClick={(e) =>{
  //           console.log('onclick select: ',e)
  //           goToPath(e.target.value)}}
  //       ></select>

  //       <h1>das ist meine ccu xml-api app</h1>
  //       <p>ich teste</p>
  //       <p></p>
  //     </div>
  //   </>
  // );

  return (
    <>
      <Link href={ROUTES.devices.path}>
        <a>Go to devices page</a>
      </Link>
    </>
  );
}

export default Home;
